### ISSUE TITLE
Tips for fine tuning the model (transfer learning)

### ISSUE THREAD

**Issue by Szustarol** [chunbolang/BAM#27]
Thank you for your great contribution with this model.
I would like to ask If transfer learning and/or fine-tuning is a sensible approach to acquire a well-functioning model.
You do provide pretrained weights for the standard datasets, however I would like to check how the model runs on different classes not present in both of those datasets.
What would be the valid approach to fine-tune this model - which layers to lock, and which models to train (for example the meta-learner only)?
Maybe fine-tuning using transfer learning is not valid for this model at all? Thank you for your answer.

**Comment by chunbolang** [comment]
Thanks for your interest!

Fine-tuning _the layers after the backbone_ of the meta-learner is an optional scheme, while this is not easy with few samples of unseen categories.

It is worth noting to check whether the current base-learner is valid for your task, in other words, whether these base categories will appear in your new images, otherwise a specific network will need to be retrained.
