### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by Ehteshamciitwah** [chunbolang/BAM#48]
Hello,
I am using your meta-learner for my custom dataset. My custom dataset has four classes each with 200 images. Each image contains more than one class. I am training on the first three classes and tested on the last class using the FSS training method. But the model is overfitted to the base classes and detecting base classes during testing on novel class.
How can I overcome overfitting on base classes?
How can I extend to multiclass segmentation so I can extract only the target class during testing? 
Any other recommendation will be appreciated. Thank you

**Comment by chunbolang** [comment]
Hello, sorry for the late reply.
1. Since the query image may contain more than one category, one can try to use it together with meta-learner and base-learner, although this requires additional training.
2. I am not sure if you mean _N_-way _K_-shot setting or generalized setting for multiclass segmentation, where the former requires meta-training the _N_-way classifier, while the latter requires the fine-tuning strategy or referencing our approach in this work.

Best,

**Comment by Ehteshamciitwah** [comment]
Thank you for your reply. Learning training classes is a built-in problem in FSS. This can be solved using base leaner as BAM or using iFSL architecture [https://github.com/dahyun-kang/ifsl](url) .
