### ISSUE TITLE
Normal mIoU, but low FB-IoU

### ISSUE THREAD

**Issue by Sam1224** [chunbolang/BAM#9]
Hi, thanks for your great work! I have trained 4 models with ResNet-50 on Pascal datasets, the mIoU is exactly what you reported (0.678), but the FB-IoU is 0.796, about 1.5% lower than reported. Would you mind release all pretrained models? Thank you so much.

**Comment by chunbolang** [comment]
@Sam1224 
Hi,
thanks for your interest!

According to our observation, compared with _mIoU_, _FB-IoU_ is more susceptible to uncertainties (_e.g._, seed, environment), leading to greater fluctuations. Therefore, advanced FSS methods tend to use the former and only take _FB-IoU_ as an auxiliary reference.

In fact, I've been struggling with other projects lately. TnT... 
I would consider releasing all trained models in the future. Sorry for the inconvenience to your research.

Regards,
Chunbo

**Comment by Sam1224** [comment]
Okay, thank you so much!

**Comment by chunbolang** [comment]
I think I know what the problem is. 
emmm... The _arxiv_ version accidentally reversed the results of vgg-5shot (81.10) and res-1shot (79.71). So your reproduction is reasonable. 

I have corrected it in the CVPR _camera-ready_ version and intend to resubmit the modified paper to _arxiv_. Sorry for this silly mistake.
